# -*- coding: utf-8 -*-
"""runModel.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cdGIrzBPJSEWdc_AwH_JRtQ6fhrFYtNG
"""

import tensorflow as tf
import tensorflow_datasets as tfds
from google.colab import drive

drive.mount('/content/gdrive')

# Load the testing set of the IMDB dataset
_, raw_test_set = tfds.load(
    name="imdb_reviews",
    split=["train", "test"],
    as_supervised=True
)

# Load the saved model
loaded_model = tf.keras.models.load_model("/content/gdrive/MyDrive/savedModel")

# Evaluate the model on the testing set
test_set = raw_test_set.batch(32).prefetch(1)
loss, accuracy = loaded_model.evaluate(test_set)

# Print the evaluation results
print("Test Loss:", loss)
print("Test Accuracy:", accuracy)